# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "667f64c91a25332d9c5dc5ec1e4ccdcb"
name = "Maisoonmaia-Final-Unique"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_draft_orders,read_marketing_events,write_draft_orders,write_marketing_events,write_orders,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
